version: '3.7'
services:
  #Apache Service
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'adelphiv2'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  #MySQL Service
  db:
    build: ./data
    image: mysql:5.7.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
      - /data/pgsql:/var/lib/postgresql
      - /data/maria:/var/lib/mariadb
      - /data/redis:/var/lib/redis
      - /data/memcached:/var/lib/memcached
      - /data/neo4j:/var/lib/neo4j/data
    environment:
      MYSQL_DATABASE: laravel_web
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
